# -*- mode: org; fill-column: 78; -*-
# Time-stamp: <2026-03-22 17:44:45 krylon>
#+TAGS: internals(i) ui(u) bug(b) feature(f)
#+TAGS: database(d) design(e), meditation(m)
#+TAGS: optimize(o) refactor(r) cleanup(c)
#+TODO: TODO(t)  RESEARCH(r) IMPLEMENT(i) TEST(e) | DONE(d) FAILED(f) CANCELLED(c)
#+TODO: MEDITATE(m) PLANNING(p) | SUSPENDED(s)
#+PRIORITIES: A G D

* Newsroom [1/2]
  :PROPERTIES:
  :COOKIE_DATA: todo recursive
  :VISIBILITY: all
  :END:
** Clocktable
   #+BEGIN: clocktable :scope file :maxlevel 255 :emphasize t
   #+CAPTION: Clock summary at [2026-03-22 So 17:44]
   | Headline                              | Time      |           |      |      |
   |---------------------------------------+-----------+-----------+------+------|
   | *Total time*                          | *1d 0:25* |           |      |      |
   |---------------------------------------+-----------+-----------+------+------|
   | *Newsroom [1/2]*                      | *1d 0:25* |           |      |      |
   | \_  /Components [1/2]/                |           | /1d 0:25/ |      |      |
   | \_    Model [0/2]                     |           |           | 0:35 |      |
   | \_    Database [0/0]                  |           |           | 3:43 |      |
   | \_    Engine [1/1]                    |           |           | 4:16 |      |
   | \_    Cache [0/2]                     |           |           | 1:44 |      |
   | \_    Rating Guesser aka Critic [0/0] |           |           | 4:54 |      |
   | \_    Web [0/2]                       |           |           | 9:13 |      |
   | \_      Rate Items                    |           |           |      | 4:52 |
   #+END:
** Components [1/2]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: all
   :END:
*** Model [0/2]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-03-09 Mo 13:15]--[2026-03-09 Mo 13:50] =>  0:35
    :END:
**** TODO Tokenizer
     In order to work with the Items in Rating and Tagging, I need to clean
     the up - strip all the HTML at the very least. Remove stopwords, stem the
     rest, etc.
**** TODO Sanitize HTML
     For display in the Web UI, I would like to sanitize the Item Body on the
     server side (ideally caching the result), remove Javascript and such,
     resize images.
*** Database [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-03-14 Sa 13:24]--[2026-03-14 Sa 13:45] =>  0:21
    CLOCK: [2026-03-10 Di 13:25]--[2026-03-10 Di 13:44] =>  0:19
    CLOCK: [2026-03-10 Di 12:39]--[2026-03-10 Di 13:23] =>  0:44
    CLOCK: [2026-03-10 Di 08:28]--[2026-03-10 Di 09:00] =>  0:32
    CLOCK: [2026-03-09 Mo 15:13]--[2026-03-09 Mo 16:01] =>  0:48
    CLOCK: [2026-03-09 Mo 14:13]--[2026-03-09 Mo 14:55] =>  0:42
    CLOCK: [2026-03-09 Mo 13:50]--[2026-03-09 Mo 14:07] =>  0:17
    :END:
*** Engine [1/1]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-03-12 Do 13:50]--[2026-03-12 Do 14:05] =>  0:15
    CLOCK: [2026-03-12 Do 13:25]--[2026-03-12 Do 13:34] =>  0:09
    CLOCK: [2026-03-11 Mi 13:56]--[2026-03-11 Mi 15:49] =>  1:53
    CLOCK: [2026-03-10 Di 13:51]--[2026-03-10 Di 15:50] =>  1:59
    :END:
**** DONE Parse RSS/Atom
     CLOSED: [2026-03-12 Do 14:15]
     https://github.com/mmcdole/gofeed
*** Cache [0/2]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-03-18 Mi 12:50]--[2026-03-18 Mi 14:34] =>  1:44
    :END:
    I am trying to use Go generics so I can use the same code for several
    purposes. But I have very little experience with Go generics, so I expect
    some trouble.
**** TODO Variable TTL
**** TODO Evict expired values
*** Classifier [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
*** Rating Guesser aka Critic [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-03-22 So 16:37]--[2026-03-22 So 17:17] =>  0:40
    CLOCK: [2026-03-21 Sa 16:27]--[2026-03-21 Sa 16:54] =>  0:27
    CLOCK: [2026-03-19 Do 17:02]--[2026-03-19 Do 18:05] =>  1:03
    CLOCK: [2026-03-19 Do 15:08]--[2026-03-19 Do 15:31] =>  0:23
    CLOCK: [2026-03-18 Mi 12:33]--[2026-03-18 Mi 12:40] =>  0:07
    CLOCK: [2026-03-16 Mo 16:56]--[2026-03-16 Mo 19:10] =>  2:14
    :END:
*** Web [0/2]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
    :LOGBOOK:
    CLOCK: [2026-03-14 Sa 13:50]--[2026-03-14 Sa 14:44] =>  0:54
    CLOCK: [2026-03-14 Sa 12:21]--[2026-03-14 Sa 12:48] =>  0:27
    CLOCK: [2026-03-12 Do 14:50]--[2026-03-12 Do 17:26] =>  2:36
    CLOCK: [2026-03-12 Do 14:16]--[2026-03-12 Do 14:40] =>  0:24
    :END:
**** TODO Rate Items
     :LOGBOOK:
     CLOCK: [2026-03-16 Mo 14:21]--[2026-03-16 Mo 15:36] =>  1:15
     CLOCK: [2026-03-16 Mo 14:00]--[2026-03-16 Mo 14:20] =>  0:20
     CLOCK: [2026-03-14 Sa 14:58]--[2026-03-14 Sa 17:50] =>  2:52
     CLOCK: [2026-03-14 Sa 12:59]--[2026-03-14 Sa 13:24] =>  0:25
     :END:
**** TODO [#F] Dark Mode?
     I switched my desktop to a dark theme the other day, after frowning upon
     those for a long time. And I gotta admit, I kind of like it. 
*** Main [0/0]
    :PROPERTIES:
    :COOKIE_DATA: todo recursive
    :VISIBILITY: all
    :END:
** Features [0/0]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: all
   :END:
*** Rating
*** Tagging
*** Analysis paralysis
    One thing that just popped up in my mind is that I could attempt to
    analyze the headlines, e.g. the frequency of certain words per day, week
    or month? That could be fun.
** Bugs [0/0]
   :PROPERTIES:
   :COOKIE_DATA: todo recursive
   :VISIBILITY: all
   :END:
