#!/usr/bin/perl
# -*- mode: cperl; coding: utf-8; -*-
# /home/krylon/go/src/github.com/blicero/newsroom/analyze/mkstopwords.pl
# created at 06. 05. 2026 by Benjamin Walkenhorst
# (c) 2026 Benjamin Walkenhorst <krylon@gmx.net>
# Time-stamp: <2026-05-06 11:54:12 krylon>
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
#  1. Redistributions of source code must retain the copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#
#  THIS SOFTWARE IS PROVIDED BY BENJAMIN WALKENHORST ``AS IS'' AND
#  ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
#  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
#  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
#  OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
#  HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
#  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
#  OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
#  SUCH DAMAGE.

use strict;
use warnings;
use diagnostics;
use utf8;
use feature qw(say);

use Carp;
use English '-no_match_vars';
use File::Slurp;
use Getopt::Long;
use IO::Handle;
use Readonly;

my $output;
my $directory;
my @files;

Readonly my %lng => (english => 'en', german => 'de');

GetOptions(
           'o|output=s' => \$output,
           'd|directory=s' => \$directory,
          );

my %words = ();

foreach my $file (glob "$directory/*.txt") {
  if ($file =~ /stop_words_([^.]+)[.]txt$/) {
    my $lang = $1;

    my @words = read_file($file, chomp => 1);

    $words{$lang} = \@words;
  } else {
    say "I don't know what to do with $file";
  }
}

open(my $fh, '>', $output)
  or die "Cannot open $output: $OS_ERROR";

$fh->write(<<'END');
// Code generated by mkstopwords.pl. DO NOT EDIT.

package analyze

var stopwords = map[string]map[string]bool{

END

while (my ($lang, $words) = each %words) {
  $fh->write("\"$lng{$lang}\": map[string]bool{\n");

  foreach my $word (@{$words}) {
    $fh->write("\t\"$word\": true,\n");
  }

  $fh->write("},\n");
}

$fh->write("}\n\n");

$fh->close();

system "gofmt", '-w', $output;


# Local Variables: #
# compile-command: "perl -c /home/krylon/go/src/github.com/blicero/newsroom/analyze/mkstopwords.pl" #
# End: #
